export { default as Home } from './Home'
export { default as SolarEnergy } from './SolarEnergy'
export { default as Contact } from './Contact'
export { default as Products } from './Products'
export { default as Services } from './Services'
